from tkinter import *
import sqlite3
root = Tk()
root.geometry('500x500')
root.configure(background="white")
root.title("Sports and Cultural Activities")
c1=StringVar()
c2=StringVar()
c3=StringVar()
s1=StringVar()
var1= IntVar()
def database():
sportname=c1.get()
name=c2.get()
branch=c3.get()
acheivement=s1.get()
national=var1.get()
conn = sqlite3.connect('module6.db')
with conn:
cursor=conn.cursor()
cursor.execute('CREATE TABLE IF NOT EXISTS Sports (sportname TEXT,name TEXT,branch TEXT,acheivement TEXT,national TEXT)')
cursor.execute('INSERT INTO Sports (sportname,name,branch,acheivement,national) VALUES(?,?,?,?,?)',(sportname,name,branch,acheivement,national,))
conn.commit()
def delete():
conn = sqlite3.connect('module6.db')
c = conn.cursor()
c.execute("DELETE from Sports")
conn.commit()
label_0 = Label(root, text="Detail Submssion",width=20,font=("bold", 20),fg="black",bg="white",height=2)
label_0.place(x=90,y=50)
label_1 = Label(root, text="Sport opted",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_1.place(x=70,y=130)
list1 = ['Football','Cricket','Tennis','Basketball','Hockey','Volleyball','Kho-Kho','Kabaddi','Athletics'];
droplist=OptionMenu(root,c1, *list1)
droplist.config(width=20)
c1.set('Select your Program') 
droplist.place(x=240,y=130)
label_2 = Label(root, text="Name",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_2.place(x=70,y=180)
entry_3 = Entry(root,textvar=c2)
entry_3.place(x=240,y=180)
label_3 = Label(root, text="Branch",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_3.place(x=70,y=230)
entry_3 = Entry(root,textvar=c3)
entry_3.place(x=240,y=230)
label_4 = Label(root, text="Acheivements",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_4.place(x=70,y=280)
entry_4 = Entry(root,textvar=s1)
entry_4.place(x=240,y=280)
label_5 = Label(root, text="Nationals",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_5.place(x=70,y=330)
var2= IntVar()
Checkbutton(root, text="Yes", variable=var1).place(x=240,y=330)
Checkbutton(root, text="No", variable=var2).place(x=290,y=330)
Button(root, text='Delete',width=20,bg='White',fg='blue',command=delete).place(x=180,y=380)
Button(root, text='Submit',width=20,bg='white',fg='blue',command=database).place(x=180,y=440)
root.mainloop()
