from tkinter import *
import sqlite3
root = Tk()
root.geometry('500x500')
root.configure(background="white")
root.title("Higher Education details")
c1=StringVar()
c2=StringVar()
c3=StringVar()
s1=IntVar()
var1= IntVar()
var2= IntVar()
def database():
 name=c1.get()
 degree=c2.get()
 institution=c3.get()
duration=s1.get()
sponsored=var1.get()
conn = sqlite3.connect('module4.db')
 with conn:
 cursor=conn.cursor()
cursor.execute('CREATE TABLE IF NOT EXISTS PostGrad (name TEXT,degree TEXT,institution TEXT, duration INTEGER,sponsored INTEGER)')
cursor.execute('INSERT INTO PostGrad (name,degree,institution,duration,sponsored) VALUES(?,?,?,?,?)',(name,institution,degree,duration,sponsored))
conn.commit()
def delete():
conn = sqlite3.connect('module4.db')
c = conn.cursor()
c.execute("DELETE from Student")
conn.commit()
label_0=Label(root,text="Studentprogression",width=25,font=("bold", 20),fg="black",bg="white",height=2)
label_0.place(x=90,y=50)
label_1 = Label(root, text="Name of student",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_1.place(x=70,y=130)
entry_1 = Entry(root,textvar=c1)
entry_1.place(x=240,y=130)
label_2 = Label(root, text="Degree pursued",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_2.place(x=70,y=180)
list1 = ['M.Tech','MBA'];
droplist=OptionMenu(root,c2, *list1)
droplist.config(width=20)
c2.set('Select your Program')
droplist.place(x=240,y=180)
label_3 = Label(root, text="Institution",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_3.place(x=70,y=230)
entry_3 = Entry(root,textvar=c3)
entry_3.place(x=240,y=230)
label_4 = Label(root, text="Duration of the degree",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_4.place(x=70,y=280)
entry_4 = Entry(root,textvar=s1)
entry_4.place(x=240,y=280)
label_5 = Label(root, text="Sponsored",width=20,font=("bold", 10),fg="black",bg="yellow",height=2)
label_5.place(x=70,y=330)
Checkbutton(root, text="Yes", variable=var1).place(x=240,y=330)
Checkbutton(root, text="No", variable=var2).place(x=290,y=330)
Button(root, text='Delete',width=20,bg='White',fg='blue',command=delete).place(x=180,y=380)
Button(root, text='Submit',width=20,bg='white',fg='blue',command=database).place(x=180,y=440)
root.mainloop()
